name: Create Versioned Branches

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  version_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Run versioning script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/scripts/version_branches.sh
