name: Version Files on Branch Change

on:
  push:
    branches: # Triggers on all branches
      - '**'

permissions:
  contents: write

jobs:
  version-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run versioning script
        run: bash .github/scripts/version_files.sh

      - name: Push changes
        run: |
          git push
